import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC", padding: 20 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 20,
    textAlign: "center",
  },
  listContainer: { paddingBottom: 20 },
  row: { justifyContent: "space-between", marginBottom: 12 },
  slotButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingVertical: 14,
    marginHorizontal: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
  },
  slotButtonSelected: { backgroundColor: "#2563EB", borderColor: "#2563EB" },
  slotText: { fontSize: 16, fontWeight: "500", color: "#334155" },
  slotTextSelected: { color: "#FFFFFF" },
  saveButton: {
    backgroundColor: "#2563EB",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  saveButtonDisabled: { backgroundColor: "#94A3B8" },
  saveButtonText: { color: "#FFFFFF", fontSize: 18, fontWeight: "bold" },
  errorText: { color: "#EF4444", fontSize: 16 },
  emptyText: {
    fontSize: 16,
    color: "#64748B",
    fontStyle: "italic",
    textAlign: "center",
  },
});
